//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMakroSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.Equipo = new HashSet<Equipo>();
        }
    
        public int PKCliente { get; set; }
        public string FKDepartamento { get; set; }
        public string FKMunicipio { get; set; }
        public string NombreCliente { get; set; }
        public string Nit { get; set; }
        public string Telefono1 { get; set; }
        public string Telefono2 { get; set; }
        public string Celular { get; set; }
        public string Direccion { get; set; }
        public string NombreRepLegal { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Correo_Electronico { get; set; }
        public string PaginaWeb { get; set; }
        public Nullable<bool> Activo { get; set; }
        public string Notas { get; set; }
    
        public virtual Departamento Departamento { get; set; }
        public virtual Municipio Municipio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equipo> Equipo { get; set; }
    }
}
