//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMakroSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compras
    {
        public int PKCompras { get; set; }
        public Nullable<int> FKProveedor { get; set; }
        public string FKDepartamento { get; set; }
        public string FKMunicipio { get; set; }
        public Nullable<System.DateTime> Fecha_Compra { get; set; }
        public string Observaciones { get; set; }
        public string Garantia { get; set; }
        public string Exterdida_Garantia { get; set; }
        public string Factura_Compra { get; set; }
        public string Ruta_Fotografia { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<decimal> Valor_Unidad { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<decimal> IVA { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<int> Cantidad_Recibida { get; set; }
        public Nullable<decimal> Saldo { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<bool> Activo { get; set; }
        public string Notas { get; set; }
    
        public virtual Departamento Departamento { get; set; }
        public virtual Municipio Municipio { get; set; }
        public virtual Proveedor Proveedor { get; set; }
    }
}
