//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMakroSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleVenta_Remision
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DetalleVenta_Remision()
        {
            this.Inventario = new HashSet<Inventario>();
            this.Remisiones = new HashSet<Remisiones>();
            this.Ventas = new HashSet<Ventas>();
        }
    
        public int PKDetalleVenta_Remision { get; set; }
        public string Dependencia { get; set; }
        public string Contactar { get; set; }
        public Nullable<System.DateTime> Fecha_Entrada { get; set; }
        public string Direccion { get; set; }
        public string Piso { get; set; }
        public string Telefono { get; set; }
        public Nullable<System.DateTime> Fecha_Salida { get; set; }
        public Nullable<bool> CPU { get; set; }
        public string NCPU { get; set; }
        public Nullable<bool> Monitor { get; set; }
        public string NMonitor { get; set; }
        public Nullable<bool> Impresora { get; set; }
        public string NImpresora { get; set; }
        public Nullable<bool> DVD { get; set; }
        public string NDVD { get; set; }
        public Nullable<bool> DiscoDuro { get; set; }
        public string NDiscoDuro { get; set; }
        public Nullable<bool> Teclado { get; set; }
        public string NTeclado { get; set; }
        public Nullable<bool> Mouse { get; set; }
        public string NMouse { get; set; }
        public Nullable<bool> Scanner { get; set; }
        public string NScanner { get; set; }
        public Nullable<bool> Office { get; set; }
        public string NOffice { get; set; }
        public string Clave_Office { get; set; }
        public Nullable<bool> Memoria { get; set; }
        public string NMemoria { get; set; }
        public Nullable<bool> Sistema_Operativo { get; set; }
        public string NSistema_Operativo { get; set; }
        public string Clave_SO { get; set; }
        public Nullable<bool> Correo { get; set; }
        public string Correo_Electronico { get; set; }
        public Nullable<bool> Antivirus { get; set; }
        public string NVAntivirus { get; set; }
        public string Clave_Antivirus { get; set; }
        public Nullable<bool> Conexion_Red { get; set; }
        public Nullable<bool> Otro { get; set; }
        public string Otros_NoReferenciado { get; set; }
        public string Nombre_Reporta { get; set; }
        public string Descripcion { get; set; }
        public string Descripcion_Detallada { get; set; }
        public Nullable<bool> Preventivo { get; set; }
        public Nullable<bool> Correctivo { get; set; }
        public string Observaciones { get; set; }
        public Nullable<System.DateTime> Fecha_Sistema { get; set; }
        public Nullable<decimal> Valor_Unidad { get; set; }
        public Nullable<decimal> IVA_Unidad { get; set; }
        public Nullable<decimal> Retencion_Unidad { get; set; }
        public Nullable<decimal> Valor_Total { get; set; }
        public Nullable<decimal> IVA_Total { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<decimal> Retencion_Total { get; set; }
        public string Notas { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventario> Inventario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Remisiones> Remisiones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ventas> Ventas { get; set; }
    }
}
