//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMakroSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipo()
        {
            this.Inventario = new HashSet<Inventario>();
            this.Mantenimiento = new HashSet<Mantenimiento>();
            this.Transaccion = new HashSet<Transaccion>();
        }
    
        public int PKEquipo { get; set; }
        public Nullable<int> FKCompras { get; set; }
        public int FKTipo { get; set; }
        public Nullable<int> FKFabricante { get; set; }
        public Nullable<int> FKProcesador { get; set; }
        public Nullable<int> FKCliente { get; set; }
        public string Sistema_Operativo { get; set; }
        public string Descripcion { get; set; }
        public string Serial { get; set; }
        public string Board { get; set; }
        public string RAM { get; set; }
        public string DiscoDuro { get; set; }
        public string Mouse { get; set; }
        public string Clave_Windows { get; set; }
        public string Clave_Office { get; set; }
        public string Clave_Antivirus { get; set; }
        public string Clave_Otros { get; set; }
        public string Clave_Otros2 { get; set; }
        public string Clave_Otros3 { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<bool> Activo { get; set; }
        public string Notas { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Fabricante Fabricante { get; set; }
        public virtual Procesador Procesador { get; set; }
        public virtual Tipo Tipo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventario> Inventario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mantenimiento> Mantenimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaccion> Transaccion { get; set; }
    }
}
