//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMakroSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventario
    {
        public int PKInventario { get; set; }
        public Nullable<int> FKTransaccion { get; set; }
        public Nullable<int> FKProveedor { get; set; }
        public int FKBodega { get; set; }
        public Nullable<int> FKDetalle_VentaRemision { get; set; }
        public Nullable<int> FKEquipo { get; set; }
        public string Factura_Compra { get; set; }
        public string Ruta_Fotografia { get; set; }
        public Nullable<System.DateTime> Fecha_Factura { get; set; }
        public Nullable<System.DateTime> Fecha_Sistema { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<decimal> Valor_Unidad { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
        public Nullable<decimal> IVA { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string Observaciones { get; set; }
        public Nullable<int> Cantidad_Recibida { get; set; }
        public Nullable<System.DateTime> Fecha_Mmto { get; set; }
        public string Planilla_Mmto { get; set; }
        public Nullable<bool> Actvo { get; set; }
        public string Notas { get; set; }
    
        public virtual Bodega Bodega { get; set; }
        public virtual DetalleVenta_Remision DetalleVenta_Remision { get; set; }
        public virtual Equipo Equipo { get; set; }
        public virtual Proveedor Proveedor { get; set; }
        public virtual Transaccion Transaccion { get; set; }
    }
}
