//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMakroSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mantenimiento
    {
        public int PKMantenimiento { get; set; }
        public Nullable<int> FKEquipo { get; set; }
        public Nullable<int> FKTecnico { get; set; }
        public Nullable<int> FKEstado { get; set; }
        public string Planilla_Mmto { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.DateTime> Fecha_Sistema { get; set; }
        public string Notas { get; set; }
    
        public virtual Equipo Equipo { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Tecnico Tecnico { get; set; }
    }
}
