//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMakroSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proveedor()
        {
            this.Compras = new HashSet<Compras>();
            this.Inventario = new HashSet<Inventario>();
        }
    
        public int PKProveedor { get; set; }
        public string FKDepartamento { get; set; }
        public string FKMunicipio { get; set; }
        public string NombreProveedor { get; set; }
        public string Nit { get; set; }
        public string Telefono1 { get; set; }
        public string Telefono2 { get; set; }
        public string Celular { get; set; }
        public string NombreContacto { get; set; }
        public string NombreContacto2 { get; set; }
        public string Servicios { get; set; }
        public string CorreoElectronico { get; set; }
        public string Paginaweb { get; set; }
        public Nullable<bool> Activo { get; set; }
        public string Notas { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Compras> Compras { get; set; }
        public virtual Departamento Departamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventario> Inventario { get; set; }
        public virtual Municipio Municipio { get; set; }
    }
}
