//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMakroSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class Remisiones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Remisiones()
        {
            this.Transaccion = new HashSet<Transaccion>();
        }
    
        public int PKRemisiones { get; set; }
        public int FKCliente { get; set; }
        public int FKProveedor { get; set; }
        public string FKDepartamento { get; set; }
        public string FKMunicipio { get; set; }
        public Nullable<int> FKDetalle_Venta_Remision { get; set; }
        public Nullable<System.DateTime> Fecha_Inicio { get; set; }
        public Nullable<System.DateTime> Fecha_Fin { get; set; }
        public System.DateTime Fecha_Sistema { get; set; }
        public Nullable<decimal> Valor_Unidad { get; set; }
        public Nullable<decimal> IVA_Unidad { get; set; }
        public Nullable<decimal> Valor_Total { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
        public Nullable<decimal> IVA { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string FVenta { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<decimal> Diferencia { get; set; }
        public Nullable<decimal> Diferencia_Precio { get; set; }
        public string Notas { get; set; }
    
        public virtual Departamento Departamento { get; set; }
        public virtual DetalleVenta_Remision DetalleVenta_Remision { get; set; }
        public virtual Municipio Municipio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaccion> Transaccion { get; set; }
    }
}
