//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMakroSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ventas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ventas()
        {
            this.Transaccion = new HashSet<Transaccion>();
        }
    
        public int PKVentas { get; set; }
        public Nullable<int> FKVendedor { get; set; }
        public Nullable<int> FKTipoDocumento { get; set; }
        public Nullable<int> FKDetalleVenta_Remision { get; set; }
        public string NombreReferencia { get; set; }
        public string Nit { get; set; }
        public string Cedula { get; set; }
        public string Telefono1 { get; set; }
        public string Telefono2 { get; set; }
        public string Celular { get; set; }
    
        public virtual DetalleVenta_Remision DetalleVenta_Remision { get; set; }
        public virtual TipoDocumento TipoDocumento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaccion> Transaccion { get; set; }
        public virtual Vendedor Vendedor { get; set; }
    }
}
